### ISSUE TITLE
BlockingIOError: [Errno 35] write could not complete without blocking ?

### ISSUE THREAD

**Issue by mmagnus** [jgreener64/mmterm#1]
```
mmterm 1FME.pdb  -m 5
1FME.pdb with 34 models, 1 chains (A), 28 residues, 504 atoms
W/A/S/D rotates, T/F/G/H moves, I/O zooms, U spins, P cycles models, Q quits
⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⡀
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡤⢄⡠⠤⠒⢤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠔⠤⢄⠤⠒⠉⠁⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡄⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠼⣀⠤⠊⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣾⡄⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠎⡖⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⢇⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡤⠶⠤⣀⡀⠀⠀⠈⢆⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⡀⠀⢀⠇⠑⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠱⢄⠀⠀⠱⠤⣀⡠⠃⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⠉⠀⠈⠑⠁⠀⢀⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡤⣀⡀⠀⠀⠀⢀⠤⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠠⡃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⢣⠀⠀⠀⡣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⠁⠀⠀⠀⠀⠑⠤⠤⢄⠀⠀⠀⠀⠀⠀⠀⠀⠈⠢⢄⠈⠉⠒⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⢠⠤⠼⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⠤⠤⡄⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⡔⠢⠼⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠱⠤⠤⠤⠒⠦⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⡰⠉⠑⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇
⣇⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⡇Traceback (most recent call last):
  File "/Users/magnus/miniconda2/envs/py37/bin/mmterm", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/magnus/work/src/mmterm/bin/mmterm", line 21, in <module>
    view_protein(args.in_file, args.format, args.model, args.chains, args.boxsize)
  File "/Users/magnus/work/src/mmterm/mmterm/view.py", line 155, in view_protein
    print(canvas.frame())
BlockingIOError: [Errno 35] write could not complete without blocking
```

**Comment by jgreener64** [comment]
I get this occasionally and don't immediately know what's causing it.

Running with a smaller box size (`-s 50`) might help.

What OS are you on? I have only tested on Linux so far.

**Comment by mmagnus** [comment]
Yeah `-s 30` helped to do more.. but then it crashes and I get the same error:

```
1FME.pdb with 34 models, 1 chains (A), 28 residues, 504 atoms
W/A/S/D rotates, T/F/G/H moves, I/O zooms, U spins, P cycles models, Q quits
⢠⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⢤
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⠀⠈⢹⠀⠀⠠⡎⠁⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⢀⠼⡡⠃⠀⠐⡥⢆⣀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠠⡃⠐⡥⠀⠀⢀⣀⡀⡤⠃⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⡴⠁⠀⢉⠆⠀⠀⠑⠓⢇⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⡣⠀⠀⠀⢇⡀⠙⢍⢷⠁⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠱⡄⠀⠀⠀⠈⠧⠤⠜⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸
⠸⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠼
1FME.pdb with 34 models, 1 chains (A), 28 residues, 504 atoms
W/A/S/D rotates, T/F/G/H moves, I/O zooms, U spins, P cycles models, Q quits
⢠⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⢤
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⠀⠈⢹⠀⠀⡤⠊⠁⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⢀⠼⡡⠃⠀⠘⡤⢆⡀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⡇⠐⡥⠀⠀⢀⣀⡀⡬⠂⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⡰⠁⠀⢉⠆⠀⠀⠑⠓⢇⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⡣⠀⠀⠀⢇⡀⠙⢍⢷⠁⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠱⡤⠀⠀⠀⠈⠧⠤⠜⠀⠀⠀⠀⠀⢸
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸
⠸⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠼Traceback (most recent call last):
  File "/Users/magnus/miniconda2/envs/py37/bin/mmterm", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/magnus/work/src/mmterm/bin/mmterm", line 21, in <module>
    view_protein(args.in_file, args.format, args.model, args.chains, args.boxsize)
  File "/Users/magnus/work/src/mmterm/mmterm/view.py", line 155, in view_protein
    print(canvas.frame())
BlockingIOError: [Errno 35] write could not complete without blocking
%                                                                                                                                                                   (py37) [mx] mmterm$ git:(master) ✗ mmterm 1FME.pdb -s 40
```

```
Python 3.7.4
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
```

**Comment by jgreener64** [comment]
Thanks, MacOS could be making it worse. I'll keep an eye out for a solution.

**Comment by mmagnus** [comment]
- https://github.com/kata-containers/runtime/issues/2467
- https://github.com/travis-ci/travis-ci/issues/8982#issuecomment-354357640

Some of the things I found yet I couldn't find a fix.

**Comment by rukibuki** [comment]
I have the exact same problem as @mmagnus 

I am also on MacOS V.10.15.5. 

tried -s 30 which works okay's -s 50 does not work at all. I can do -s up 49 anything above that and it crashes.

Im on Python 3.8.3

Any ideas on what to do to fix this, I would really like to use mmterm!

Ruki

**Comment by jgreener64** [comment]
I'm not sure I have the time to dig into this, and if it is a MacOS issue I don't have access to one.

Perhaps have a look at the linked issues above if you want to have a go at fixing it, otherwise you can change the default `-s` to 49 in the script and use it with the smaller window.

**Comment by rukibuki** [comment]
To bad this was exactly what I was looking for with all of the remote SSH login I do looking for PDB files etc. This would have been great. Heres hoping you or anyone else figures it out.

cheers

Ruki

**Comment by jgreener64** [comment]
This should be fixed by the above PR, if not then please re-open.
