### ISSUE TITLE
curses.error: addwstr() returned ERR in macOS Monterey

### ISSUE THREAD

**Issue by mjfos2r** [jgreener64/mmterm#6]
System: Macbook Pro 
CPU:M1 pro
OS: macOS Monterey 12.3.1
Problem: When viewing .cif models, attempting to launch mmterm in a window smaller than 53x29 causes the following error. 
Description: when terminal window width <53 || height <29:
Error:
`
Traceback (most recent call last):
                 File "/usr/local/bin/mmterm", line 21, in <module>
                  view(args.in_file, args.format, args.model, args.chains, args.boxsize)
                                     File "/Users/michael/bioinformatics/mmterm/mmterm/view.py", line 251, in view
                  window_structure.addstr(0, 0, canvas.frame())
          _curses.error: addwstr() returned ERR
`
Workaround: manually resize terminal window to larger than 52x28
Possible Solution: include check during init & resize to minimum if smaller than req.

**Comment by jgreener64** [comment]
Thanks for reporting this. I don't have time to fix it currently though.
